import { writeFileSync } from "node:fs";
import { guardianCollusion, linkability, regulatorView, smallRegion, sybil, timing } from "./attacks.mjs";

const results = [linkability(), timing(), smallRegion(), await guardianCollusion(), sybil(), regulatorView()];
writeFileSync(new URL("./results.json", import.meta.url), JSON.stringify(results, null, 2));

let md = "# Red-team results\n\nGenerated by `npm start -w redteam`. Each attack maps to a row of the threat model in `docs/THREAT_MODEL.md`.\n\n";
md += "| ID | Attack | Verdict |\n|---|---|---|\n" + results.map((r) => `| ${r.id} | ${r.name} | ${r.verdict} |`).join("\n") + "\n";
for (const r of results) {
  md += `\n## ${r.id} · ${r.name}\n\n\`\`\`json\n${JSON.stringify(r, null, 2)}\n\`\`\`\n`;
}
writeFileSync(new URL("./REPORT.md", import.meta.url), md);
for (const r of results) console.log(`${r.id}  ${r.verdict}`);
