const path = require("path");
const { expect } = require("chai");
const { ethers } = require("hardhat");
const { deployLotus, ROLE } = require("../scripts/deploy-lib");
const { ZERO32 } = require("./helpers");

const ZK = path.join(__dirname, "..", "..", "apps", "web", "public", "zk");
const WASM = path.join(ZK, "lotus_membership.wasm");
const ZKEY = path.join(ZK, "lotus_final.zkey");

/**
 * Uses the real Groth16 verifier generated by circuits/setup.sh and real proofs from snarkjs.
 * This is the proof that features A and B are anonymous AND sound, not just mocked.
 */
describe("Real zero-knowledge proofs (Groth16 verifier)", function () {
  this.timeout(240_000);
  let f, sdk, snarkjs, lotKey, alice, bob, leaves;

  before(async () => {
    sdk = await import("@lotus/sdk");
    snarkjs = require("snarkjs");
    const [admin, mfr, pharm, doctor, regulator] = await ethers.getSigners();
    const verifier = await ethers.deployContract("Groth16Verifier");
    f = await deployLotus({ admin, verifier: await verifier.getAddress(), safetySignalThreshold: 2 });
    for (const [s, r] of [[mfr, "MANUFACTURER"], [pharm, "PHARMACY"], [doctor, "PRESCRIBER"], [regulator, "REGULATOR"]]) {
      await f.roles.registerActor(s.address, ROLE[r], 1);
    }
    Object.assign(f, { mfr, pharm, doctor, regulator });
    const now = (await ethers.provider.getBlock("latest")).timestamp;
    await f.batches.connect(mfr).registerLot("0002-1433-80", "ZK-1", now + 1e7, ZERO32, 100);
    lotKey = await f.batches.lotKeyOf("0002-1433-80", "ZK-1");
    await f.custody.connect(mfr).ship(lotKey, pharm.address, 100, ZERO32);
    await f.custody.connect(pharm).accept(0);

    alice = sdk.newPatientSecret();
    bob = sdk.newPatientSecret();
    leaves = [];
    // leaf 0: Bob (his dispense #0), leaf 1: Alice (#0), leaf 2: Bob again (#1)
    for (const [secret, index] of [[bob, 0], [alice, 0], [bob, 1]]) {
      const { permitSecret, holderCommit } = sdk.newPermit();
      const permitId = await f.prescriptions.permitCount();
      await f.prescriptions.connect(doctor).issue(holderCommit, "0002-1433-80", 1, now + 1e6);
      const commitment = sdk.commitmentAt(secret, index);
      leaves.push(commitment);
      await f.dispenses.connect(pharm).dispense({ lotKey, permitId, permitSecret, qty: 1, commitment, shipmentRef: ZERO32 });
    }
  });

  const prove = (secret, index, leafIndex, externalNullifier, signalHash) =>
    sdk.proveMembership({ snarkjs, wasm: WASM, zkey: ZKEY, secret, index, leaves, leafIndex, externalNullifier, signalHash });

  it("accepts a real proof for an adverse-event report and rejects the replay", async () => {
    const reportCid = ethers.id("rash after 2 days");
    const z = await prove(alice, 0, 1, sdk.externalNullifierForReport(lotKey), sdk.reportSignalHash(4, reportCid));
    await expect(f.signals.reportAdverseEvent(lotKey, z.root, z.nullifierHash, 4, reportCid, z.proof)).to.emit(f.signals, "AdverseEventReported");
    await expect(f.signals.reportAdverseEvent(lotKey, z.root, z.nullifierHash, 4, reportCid, z.proof)).to.be.revertedWith("Signals: already used");
  });

  it("rejects a proof whose report contents were changed by a relayer", async () => {
    const z = await prove(bob, 0, 0, sdk.externalNullifierForReport(lotKey), sdk.reportSignalHash(2, ZERO32));
    await expect(f.signals.reportAdverseEvent(lotKey, z.root, z.nullifierHash, 5, ZERO32, z.proof)).to.be.revertedWith("Signals: invalid proof");
  });

  it("a non-recipient cannot produce a valid proof", async () => {
    const mallory = sdk.newPatientSecret();
    await expect(prove(mallory, 0, 1, sdk.externalNullifierForReport(lotKey), 1n)).to.be.rejected; // circuit constraint fails
  });

  it("one patient with two dispenses still reports only once per lot (nullifier is per patient)", async () => {
    const ext = sdk.externalNullifierForReport(lotKey);
    const z1 = await prove(bob, 0, 0, ext, sdk.reportSignalHash(3, ZERO32));
    await f.signals.reportAdverseEvent(lotKey, z1.root, z1.nullifierHash, 3, ZERO32, z1.proof);
    const z2 = await prove(bob, 1, 2, ext, sdk.reportSignalHash(3, ZERO32));
    expect(z2.nullifierHash).to.equal(z1.nullifierHash);
    await expect(f.signals.reportAdverseEvent(lotKey, z2.root, z2.nullifierHash, 3, ZERO32, z2.proof)).to.be.revertedWith("Signals: already used");
  });

  it("acknowledges a recall with a real proof and updates effectiveness", async () => {
    await f.recalls.connect(f.regulator).issueRecall(lotKey, 1, ZERO32, false);
    const z = await prove(alice, 0, 1, sdk.externalNullifierForAck(0), sdk.ackSignalHash(2));
    await f.signals.acknowledgeRecall(0, z.root, z.nullifierHash, 2, z.proof);
    expect(await f.signals.ackCount(0)).to.equal(1);
  });
});
